// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAByAEQFGzTYsK0YoqqM--NUcEtSOKfn6c',
    appId: '1:994130837429:web:dc1c6d46a8a57d0942a3fc',
    messagingSenderId: '994130837429',
    projectId: 'quickfoodies-7c28d',
    authDomain: 'quickfoodies-7c28d.firebaseapp.com',
    storageBucket: 'quickfoodies-7c28d.appspot.com',
    measurementId: 'G-W737NPQQHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBtbp6BxxPlKFE4I9OnBiImU7-sX8fJQI',
    appId: '1:994130837429:android:4c2067a53ad2398742a3fc',
    messagingSenderId: '994130837429',
    projectId: 'quickfoodies-7c28d',
    storageBucket: 'quickfoodies-7c28d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTlNdRpaOY0_WmKC4neyTqlrUuyi0zt0k',
    appId: '1:994130837429:ios:38898476f45524eb42a3fc',
    messagingSenderId: '994130837429',
    projectId: 'quickfoodies-7c28d',
    storageBucket: 'quickfoodies-7c28d.appspot.com',
    iosBundleId: 'com.example.quickFoodies',
  );
}
